name = "hotnews"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2025-4-28"

[[d1_databases]]
binding = "HOTNEWS_DB"
database_name = "hotnews-db"
database_id = "bf153967-1ca5-4ad8-accb-667ceadd49e4"
